export const FETCH_BOOKS = 'FETCH_BOOKS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const DELETE_FROM_WISHLIST = 'DELETE_FROM_WISHLIST';
export const OPEN_CART = 'OPEN_CART';
export const OPEN_WISHLIST = 'OPEN_WISHLIST';
export const INCREMENT_CART_PRODUCTS = 'INCREMENT_CART_PRODUCTS';
export const DECREMENT_CART_PRODUCTS = 'DECREMENT_CART_PRODUCTS';
export const INCREMENT_WISHLIST_PRODUCTS = 'INCREMENT_WISHLIST_PRODUCTS';
export const DECREMENT_WISHLIST_PRODUCTS = 'DECREMENT_WISHLIST_PRODUCTS';
export const GET_CART_COUNTS = 'GET_CART_COUNTS'
export const GET_WISHLIST_COUNTS = 'GET_WISHLIST_COUNTS'


